---
title: "Kural 1"
format: revealjs
auto-slide: 500
loop: false
---

# Kural 1

## Kural 1-1

###  அக

## Kural 1-1

###  அகர

## Kural 1-2

###  அகர முத

## Kural 1-2

###  அகர முதல 

## Kural 1-3

###  அகர முதல எழுத்

## Kural 1-3

###  அகர முதல எழுத்தெல்

## Kural 1-3

###  அகர முதல எழுத்தெல்லாம்

## Kural 1-4

###  அகர முதல எழுத்தெல்லாம் ஆ

## Kural 1-4

###  அகர முதல எழுத்தெல்லாம் ஆதி

## Kural 1-5

###  அகர முதல எழுத்தெல்லாம் ஆதி 

### பக

## Kural 1-5

###  அகர முதல எழுத்தெல்லாம் ஆதி 

### பகவன்

## Kural 1-6

###  அகர முதல எழுத்தெல்லாம் ஆதி 

### பகவன் முதற்

## Kural 1-6

###  அகர முதல எழுத்தெல்லாம் ஆதி 

### பகவன் முதற்றே

## Kural 1-7

###  அகர முதல எழுத்தெல்லாம் ஆதி 

### பகவன் முதற்றே  உல

## Kural 1-7

###  அகர முதல எழுத்தெல்லாம் ஆதி 

### பகவன் முதற்றே  உலகு

# Kural 12

## Kural 12-1

### துப்

## Kural 12-1

### துப்பார்க்

## Kural 12-1

### துப்பார்க்குத்

## Kural 12-2

### துப்பார்க்குத் துப்

## Kural 12-2

### துப்பார்க்குத் துப்பா

## Kural 12-2

### துப்பார்க்குத் துப்பாய

## Kural 12-3

### துப்பார்க்குத் துப்பாய துப்

## Kural 12-3

### துப்பார்க்குத் துப்பாய துப்பாக்

## Kural 12-3

### துப்பார்க்குத் துப்பாய துப்பாக்கித்

## Kural 12-4

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்

## Kural 12-4

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்

## Kural 12-4

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்

## Kural 12-5

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்
### துப்

## Kural 12-5

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்
### துப்பா

## Kural 12-5

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்
### துப்பாய

## Kural 12-6

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்
### துப்பாய தூ

## Kural 12-6

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்
### துப்பாய தூஉம்

## Kural 12-7

### துப்பார்க்குத் துப்பாய துப்பாக்கித் துப்பார்க்குத்
### துப்பாய தூஉம் மழை

# Kural 23

## Kural 23-1

### இரு

## Kural 23-1

### இருமை

## Kural 23-2

### இருமை வகை

## Kural 23-2

### இருமை வகைதெரிந்

## Kural 23-2

### இருமை வகைதெரிந்து

## Kural 23-3

### இருமை வகைதெரிந்து ஈண்

## Kural 23-3

### இருமை வகைதெரிந்து ஈண்டுஅ

## Kural 23-3

### இருமை வகைதெரிந்து ஈண்டுஅறம்

## Kural 23-4

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்

## Kural 23-4

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்

## Kural 23-5

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெரு

## Kural 23-5

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெருமை

## Kural 23-6

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெருமை பிறங்

## Kural 23-6

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெருமை பிறங்கிற்

## Kural 23-6

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெருமை பிறங்கிற்று

## Kural 23-7

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெருமை பிறங்கிற்று உல

## Kural 23-7

### இருமை வகைதெரிந்து ஈண்டுஅறம் பூண்டார்
### பெருமை பிறங்கிற்று உலகு

# Kural 34

## Kural 34-1

### மனத்

## Kural 34-1

### மனத்துக்

## Kural 34-1

### மனத்துக்கண்

## Kural 34-2

### மனத்துக்கண் மா

## Kural 34-2

### மனத்துக்கண் மாசிலன்

## Kural 34-3

### மனத்துக்கண் மாசிலன் ஆ

## Kural 34-3

### மனத்துக்கண் மாசிலன் ஆதல்

## Kural 34-4

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்

## Kural 34-4

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்

## Kural 34-5

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்
### ஆ

## Kural 34-5

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்
### ஆகுல

## Kural 34-6

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்
### ஆகுல நீ

## Kural 34-6

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்
### ஆகுல நீர

## Kural 34-7

### மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்
### ஆகுல நீர பிற

# Kural 45

## Kural 45-1

### அன்

## Kural 45-1

### அன்பும்

## Kural 45-2

### அன்பும் அற

## Kural 45-2

### அன்பும் அறனும்

## Kural 45-3

### அன்பும் அறனும் உடைத்

## Kural 45-3

### அன்பும் அறனும் உடைத்தா

## Kural 45-3

### அன்பும் அறனும் உடைத்தாயின்

## Kural 45-4

### அன்பும் அறனும் உடைத்தாயின் இல்

## Kural 45-4

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்

## Kural 45-4

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்கை

## Kural 45-5

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்கை
### பண்

## Kural 45-5

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்கை
### பண்பும்

## Kural 45-6

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்கை
### பண்பும் பய

## Kural 45-6

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்கை
### பண்பும் பயனும்

## Kural 45-7

### அன்பும் அறனும் உடைத்தாயின் இல்வாழ்க்கை
### பண்பும் பயனும் அது

# Kural 56

## Kural 56-1

### தற்

## Kural 56-1

### தற்காத்

## Kural 56-1

### தற்காத்துத்

## Kural 56-2

### தற்காத்துத் தற்

## Kural 56-2

### தற்காத்துத் தற்கொண்

## Kural 56-2

### தற்காத்துத் தற்கொண்டாற்

## Kural 56-3

### தற்காத்துத் தற்கொண்டாற் பே

## Kural 56-3

### தற்காத்துத் தற்கொண்டாற் பேணித்

## Kural 56-4

### தற்காத்துத் தற்கொண்டாற் பேணித் தகை

## Kural 56-4

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்

## Kural 56-4

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற

## Kural 56-5

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற
### சொற்

## Kural 56-5

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற
### சொற்காத்

## Kural 56-5

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற
### சொற்காத்துச்

## Kural 56-6

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற
### சொற்காத்துச் சோர்

## Kural 56-6

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற
### சொற்காத்துச் சோர்விலாள்

## Kural 56-7

### தற்காத்துத் தற்கொண்டாற் பேணித் தகைசான்ற
### சொற்காத்துச் சோர்விலாள் பெண்

# Kural 67

## Kural 67-1

### தந்

## Kural 67-1

### தந்தை

## Kural 67-2

### தந்தை மகற்

## Kural 67-2

### தந்தை மகற்காற்

## Kural 67-2

### தந்தை மகற்காற்று

## Kural 67-3

### தந்தை மகற்காற்று நன்

## Kural 67-3

### தந்தை மகற்காற்று நன்றி

## Kural 67-4

### தந்தை மகற்காற்று நன்றி அவை

## Kural 67-4

### தந்தை மகற்காற்று நன்றி அவையத்

## Kural 67-4

### தந்தை மகற்காற்று நன்றி அவையத்து

## Kural 67-5

### தந்தை மகற்காற்று நன்றி அவையத்து
### முந்

## Kural 67-5

### தந்தை மகற்காற்று நன்றி அவையத்து
### முந்தி

## Kural 67-6

### தந்தை மகற்காற்று நன்றி அவையத்து
### முந்தி இருப்

## Kural 67-6

### தந்தை மகற்காற்று நன்றி அவையத்து
### முந்தி இருப்பச்

## Kural 67-7

### தந்தை மகற்காற்று நன்றி அவையத்து
### முந்தி இருப்பச் செயல்

# Kural 78

## Kural 78-1

### அன்

## Kural 78-1

### அன்பகத்

## Kural 78-2

### அன்பகத் தில்

## Kural 78-2

### அன்பகத் தில்லா

## Kural 78-3

### அன்பகத் தில்லா உயிர்

## Kural 78-3

### அன்பகத் தில்லா உயிர்வாழ்க்

## Kural 78-3

### அன்பகத் தில்லா உயிர்வாழ்க்கை

## Kural 78-4

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்

## Kural 78-4

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்

## Kural 78-4

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்

## Kural 78-5

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்
### வற்

## Kural 78-5

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்
### வற்றல்

## Kural 78-6

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்
### வற்றல் மரந்

## Kural 78-6

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்
### வற்றல் மரந்தளிர்த்

## Kural 78-7

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்
### வற்றல் மரந்தளிர்த் தற்

## Kural 78-7

### அன்பகத் தில்லா உயிர்வாழ்க்கை வன்பாற்கண்
### வற்றல் மரந்தளிர்த் தற்று

# Kural 89

## Kural 89-1

### உடை

## Kural 89-1

### உடைமை

## Kural 89-1

### உடைமையுள்

## Kural 89-2

### உடைமையுள் இன்

## Kural 89-2

### உடைமையுள் இன்மை

## Kural 89-3

### உடைமையுள் இன்மை விருந்

## Kural 89-3

### உடைமையுள் இன்மை விருந்தோம்

## Kural 89-3

### உடைமையுள் இன்மை விருந்தோம்பல்

## Kural 89-4

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்

## Kural 89-4

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா

## Kural 89-5

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மட

## Kural 89-5

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மடமை

## Kural 89-6

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மடமை மட

## Kural 89-6

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மடமை மடவார்

## Kural 89-6

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மடமை மடவார்கண்

## Kural 89-7

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மடமை மடவார்கண் உண்

## Kural 89-7

### உடைமையுள் இன்மை விருந்தோம்பல் ஓம்பா
### மடமை மடவார்கண் உண்டு

# Kural 100

## Kural 100-1

### இனி

## Kural 100-1

### இனிய

## Kural 100-2

### இனிய உள

## Kural 100-2

### இனிய உளவா

## Kural 100-2

### இனிய உளவாக

## Kural 100-3

### இனிய உளவாக இன்

## Kural 100-3

### இனிய உளவாக இன்னா

## Kural 100-3

### இனிய உளவாக இன்னாத

## Kural 100-4

### இனிய உளவாக இன்னாத கூ

## Kural 100-4

### இனிய உளவாக இன்னாத கூறல்

## Kural 100-5

### இனிய உளவாக இன்னாத கூறல்
### கனி

## Kural 100-5

### இனிய உளவாக இன்னாத கூறல்
### கனிஇருப்

## Kural 100-5

### இனிய உளவாக இன்னாத கூறல்
### கனிஇருப்பக்

## Kural 100-6

### இனிய உளவாக இன்னாத கூறல்
### கனிஇருப்பக் காய்

## Kural 100-6

### இனிய உளவாக இன்னாத கூறல்
### கனிஇருப்பக் காய்கவர்ந்

## Kural 100-7

### இனிய உளவாக இன்னாத கூறல்
### கனிஇருப்பக் காய்கவர்ந் தற்

## Kural 100-7

### இனிய உளவாக இன்னாத கூறல்
### கனிஇருப்பக் காய்கவர்ந் தற்று

# Kural 101

## Kural 101-1

### செய்

## Kural 101-1

### செய்யா

## Kural 101-1

### செய்யாமல்

## Kural 101-2

### செய்யாமல் செய்

## Kural 101-2

### செய்யாமல் செய்த

## Kural 101-3

### செய்யாமல் செய்த உத

## Kural 101-3

### செய்யாமல் செய்த உதவிக்

## Kural 101-3

### செய்யாமல் செய்த உதவிக்கு

## Kural 101-4

### செய்யாமல் செய்த உதவிக்கு வை

## Kural 101-4

### செய்யாமல் செய்த உதவிக்கு வையக

## Kural 101-4

### செய்யாமல் செய்த உதவிக்கு வையகமும்

## Kural 101-5

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வா

## Kural 101-5

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வானக

## Kural 101-5

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வானகமும்

## Kural 101-6

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வானகமும் ஆற்

## Kural 101-6

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வானகமும் ஆற்றல்

## Kural 101-7

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வானகமும் ஆற்றல் அரி

## Kural 101-7

### செய்யாமல் செய்த உதவிக்கு வையகமும்
### வானகமும் ஆற்றல் அரிது

# Kural 112

## Kural 112-1

### செப்

## Kural 112-1

### செப்பம்

## Kural 112-2

### செப்பம் உடை

## Kural 112-2

### செப்பம் உடையவன்

## Kural 112-3

### செப்பம் உடையவன் ஆக்

## Kural 112-3

### செப்பம் உடையவன் ஆக்கஞ்

## Kural 112-4

### செப்பம் உடையவன் ஆக்கஞ் சிதை

## Kural 112-4

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்

## Kural 112-4

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி

## Kural 112-5

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்

## Kural 112-5

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்

## Kural 112-5

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்திற்

## Kural 112-6

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்திற் கே

## Kural 112-6

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்திற் கேமாப்

## Kural 112-6

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்திற் கேமாப்பு

## Kural 112-7

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்திற் கேமாப்பு உடைத்

## Kural 112-7

### செப்பம் உடையவன் ஆக்கஞ் சிதைவின்றி
### எச்சத்திற் கேமாப்பு உடைத்து

# Kural 123

## Kural 123-1

### செறி

## Kural 123-1

### செறிவறிந்

## Kural 123-1

### செறிவறிந்து

## Kural 123-2

### செறிவறிந்து சீர்

## Kural 123-2

### செறிவறிந்து சீர்மை

## Kural 123-3

### செறிவறிந்து சீர்மை பயக்

## Kural 123-3

### செறிவறிந்து சீர்மை பயக்கும்

## Kural 123-4

### செறிவறிந்து சீர்மை பயக்கும் அறி

## Kural 123-4

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்

## Kural 123-4

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்து

## Kural 123-5

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்து
### ஆற்

## Kural 123-5

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்து
### ஆற்றின்

## Kural 123-6

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்து
### ஆற்றின் அடங்

## Kural 123-6

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்து
### ஆற்றின் அடங்கப்

## Kural 123-7

### செறிவறிந்து சீர்மை பயக்கும் அறிவறிந்து
### ஆற்றின் அடங்கப் பெறின்

# Kural 134

## Kural 134-1

### மறப்

## Kural 134-1

### மறப்பினும்

## Kural 134-2

### மறப்பினும் ஓத்

## Kural 134-2

### மறப்பினும் ஓத்துக்

## Kural 134-3

### மறப்பினும் ஓத்துக் கொள

## Kural 134-3

### மறப்பினும் ஓத்துக் கொளலா

## Kural 134-3

### மறப்பினும் ஓத்துக் கொளலாகும்

## Kural 134-4

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்

## Kural 134-4

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்

## Kural 134-5

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்
### பிறப்

## Kural 134-5

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்
### பிறப்பொழுக்

## Kural 134-5

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்
### பிறப்பொழுக்கங்

## Kural 134-6

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்
### பிறப்பொழுக்கங் குன்

## Kural 134-6

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்
### பிறப்பொழுக்கங் குன்றக்

## Kural 134-7

### மறப்பினும் ஓத்துக் கொளலாகும் பார்ப்பான்
### பிறப்பொழுக்கங் குன்றக் கெடும்

# Kural 145

## Kural 145-1

### எளி

## Kural 145-1

### எளிதென

## Kural 145-2

### எளிதென இல்

## Kural 145-2

### எளிதென இல்லிறப்

## Kural 145-2

### எளிதென இல்லிறப்பான்

## Kural 145-3

### எளிதென இல்லிறப்பான் எய்

## Kural 145-3

### எளிதென இல்லிறப்பான் எய்துமெஞ்

## Kural 145-4

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்

## Kural 145-4

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்

## Kural 145-5

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்
### விளி

## Kural 145-5

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்
### விளியா

## Kural 145-5

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்
### விளியாது

## Kural 145-6

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்
### விளியாது நிற்

## Kural 145-6

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்
### விளியாது நிற்கும்

## Kural 145-7

### எளிதென இல்லிறப்பான் எய்துமெஞ் ஞான்றும்
### விளியாது நிற்கும் பழி

# Kural 156

## Kural 156-1

### ஒறுத்

## Kural 156-1

### ஒறுத்தார்க்

## Kural 156-1

### ஒறுத்தார்க்கு

## Kural 156-2

### ஒறுத்தார்க்கு ஒரு

## Kural 156-2

### ஒறுத்தார்க்கு ஒருநா

## Kural 156-2

### ஒறுத்தார்க்கு ஒருநாளை

## Kural 156-3

### ஒறுத்தார்க்கு ஒருநாளை இன்

## Kural 156-3

### ஒறுத்தார்க்கு ஒருநாளை இன்பம்

## Kural 156-4

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்

## Kural 156-4

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்

## Kural 156-4

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்குப்

## Kural 156-5

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்குப்
### பொன்

## Kural 156-5

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்குப்
### பொன்றுந்

## Kural 156-6

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்குப்
### பொன்றுந் துணை

## Kural 156-6

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்குப்
### பொன்றுந் துணையும்

## Kural 156-7

### ஒறுத்தார்க்கு ஒருநாளை இன்பம் பொறுத்தார்க்குப்
### பொன்றுந் துணையும் புகழ்

# Kural 167

## Kural 167-1

### அவ்

## Kural 167-1

### அவ்வித்

## Kural 167-1

### அவ்வித்து

## Kural 167-2

### அவ்வித்து அழுக்

## Kural 167-2

### அவ்வித்து அழுக்கா

## Kural 167-2

### அவ்வித்து அழுக்காறு

## Kural 167-3

### அவ்வித்து அழுக்காறு உடை

## Kural 167-3

### அவ்வித்து அழுக்காறு உடையா

## Kural 167-3

### அவ்வித்து அழுக்காறு உடையானைச்

## Kural 167-4

### அவ்வித்து அழுக்காறு உடையானைச் செய்

## Kural 167-4

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்

## Kural 167-5

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்
### தவ்

## Kural 167-5

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்
### தவ்வை

## Kural 167-5

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்
### தவ்வையைக்

## Kural 167-6

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்
### தவ்வையைக் காட்

## Kural 167-6

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்
### தவ்வையைக் காட்டி

## Kural 167-7

### அவ்வித்து அழுக்காறு உடையானைச் செய்யவள்
### தவ்வையைக் காட்டி விடும்

# Kural 178

## Kural 178-1

### அஃ

## Kural 178-1

### அஃகா

## Kural 178-1

### அஃகாமை

## Kural 178-2

### அஃகாமை செல்

## Kural 178-2

### அஃகாமை செல்வத்

## Kural 178-2

### அஃகாமை செல்வத்திற்

## Kural 178-3

### அஃகாமை செல்வத்திற் கியா

## Kural 178-3

### அஃகாமை செல்வத்திற் கியாதெனின்

## Kural 178-4

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃ

## Kural 178-4

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகா

## Kural 178-4

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகாமை

## Kural 178-5

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகாமை
### வேண்

## Kural 178-5

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகாமை
### வேண்டும்

## Kural 178-6

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகாமை
### வேண்டும் பிறன்

## Kural 178-6

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகாமை
### வேண்டும் பிறன்கைப்

## Kural 178-7

### அஃகாமை செல்வத்திற் கியாதெனின் வெஃகாமை
### வேண்டும் பிறன்கைப் பொருள்

# Kural 189

## Kural 189-1

### அறன்

## Kural 189-1

### அறன்நோக்

## Kural 189-1

### அறன்நோக்கி

## Kural 189-2

### அறன்நோக்கி ஆற்

## Kural 189-2

### அறன்நோக்கி ஆற்றுங்

## Kural 189-2

### அறன்நோக்கி ஆற்றுங்கொல்

## Kural 189-3

### அறன்நோக்கி ஆற்றுங்கொல் வை

## Kural 189-3

### அறன்நோக்கி ஆற்றுங்கொல் வையம்

## Kural 189-4

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்

## Kural 189-4

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்

## Kural 189-4

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்கிப்

## Kural 189-5

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்கிப்
### புன்

## Kural 189-5

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்கிப்
### புன்சொல்

## Kural 189-6

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்கிப்
### புன்சொல் உரைப்

## Kural 189-6

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்கிப்
### புன்சொல் உரைப்பான்

## Kural 189-7

### அறன்நோக்கி ஆற்றுங்கொல் வையம் புறன்நோக்கிப்
### புன்சொல் உரைப்பான் பொறை

# Kural 200

## Kural 200-1

### சொல்

## Kural 200-1

### சொல்லுக

## Kural 200-2

### சொல்லுக சொல்

## Kural 200-2

### சொல்லுக சொல்லிற்

## Kural 200-3

### சொல்லுக சொல்லிற் பய

## Kural 200-3

### சொல்லுக சொல்லிற் பயனுடை

## Kural 200-3

### சொல்லுக சொல்லிற் பயனுடைய

## Kural 200-4

### சொல்லுக சொல்லிற் பயனுடைய சொல்

## Kural 200-4

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்

## Kural 200-4

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்க

## Kural 200-5

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்க
### சொல்

## Kural 200-5

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்க
### சொல்லிற்

## Kural 200-6

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்க
### சொல்லிற் பய

## Kural 200-6

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்க
### சொல்லிற் பயனிலாச்

## Kural 200-7

### சொல்லுக சொல்லிற் பயனுடைய சொல்லற்க
### சொல்லிற் பயனிலாச் சொல்

# Kural 201

## Kural 201-1

### தீ

## Kural 201-1

### தீவினை

## Kural 201-1

### தீவினையார்

## Kural 201-2

### தீவினையார் அஞ்

## Kural 201-2

### தீவினையார் அஞ்சார்

## Kural 201-3

### தீவினையார் அஞ்சார் விழு

## Kural 201-3

### தீவினையார் அஞ்சார் விழுமியார்

## Kural 201-4

### தீவினையார் அஞ்சார் விழுமியார் அஞ்

## Kural 201-4

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்

## Kural 201-5

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்
### தீ

## Kural 201-5

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்
### தீவினை

## Kural 201-6

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்
### தீவினை என்

## Kural 201-6

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்
### தீவினை என்னும்

## Kural 201-7

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்
### தீவினை என்னும் செருக்

## Kural 201-7

### தீவினையார் அஞ்சார் விழுமியார் அஞ்சுவர்
### தீவினை என்னும் செருக்கு

# Kural 212

## Kural 212-1

### தா

## Kural 212-1

### தாளாற்

## Kural 212-1

### தாளாற்றித்

## Kural 212-2

### தாளாற்றித் தந்

## Kural 212-2

### தாளாற்றித் தந்த

## Kural 212-3

### தாளாற்றித் தந்த பொரு

## Kural 212-3

### தாளாற்றித் தந்த பொருளெல்

## Kural 212-3

### தாளாற்றித் தந்த பொருளெல்லாம்

## Kural 212-4

### தாளாற்றித் தந்த பொருளெல்லாம் தக்

## Kural 212-4

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்

## Kural 212-4

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு

## Kural 212-5

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வே

## Kural 212-5

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வேளாண்

## Kural 212-5

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வேளாண்மை

## Kural 212-6

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வேளாண்மை செய்

## Kural 212-6

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வேளாண்மை செய்தற்

## Kural 212-7

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வேளாண்மை செய்தற் பொருட்

## Kural 212-7

### தாளாற்றித் தந்த பொருளெல்லாம் தக்கார்க்கு
### வேளாண்மை செய்தற் பொருட்டு

# Kural 223

## Kural 223-1

### இல

## Kural 223-1

### இலனென்

## Kural 223-1

### இலனென்னும்

## Kural 223-2

### இலனென்னும் எவ்

## Kural 223-2

### இலனென்னும் எவ்வம்

## Kural 223-3

### இலனென்னும் எவ்வம் உரை

## Kural 223-3

### இலனென்னும் எவ்வம் உரையா

## Kural 223-3

### இலனென்னும் எவ்வம் உரையாமை

## Kural 223-4

### இலனென்னும் எவ்வம் உரையாமை ஈ

## Kural 223-4

### இலனென்னும் எவ்வம் உரையாமை ஈதல்

## Kural 223-5

### இலனென்னும் எவ்வம் உரையாமை ஈதல்
### குல

## Kural 223-5

### இலனென்னும் எவ்வம் உரையாமை ஈதல்
### குலனுடை

## Kural 223-5

### இலனென்னும் எவ்வம் உரையாமை ஈதல்
### குலனுடையான்

## Kural 223-6

### இலனென்னும் எவ்வம் உரையாமை ஈதல்
### குலனுடையான் கண்

## Kural 223-6

### இலனென்னும் எவ்வம் உரையாமை ஈதல்
### குலனுடையான் கண்ணே

## Kural 223-7

### இலனென்னும் எவ்வம் உரையாமை ஈதல்
### குலனுடையான் கண்ணே யுள

# Kural 234

## Kural 234-1

### நில

## Kural 234-1

### நிலவரை

## Kural 234-2

### நிலவரை நீள்

## Kural 234-2

### நிலவரை நீள்புகழ்

## Kural 234-3

### நிலவரை நீள்புகழ் ஆற்

## Kural 234-3

### நிலவரை நீள்புகழ் ஆற்றின்

## Kural 234-4

### நிலவரை நீள்புகழ் ஆற்றின் புல

## Kural 234-4

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்

## Kural 234-5

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்

## Kural 234-5

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்றா

## Kural 234-5

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்றாது

## Kural 234-6

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்றாது புத்

## Kural 234-6

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்றாது புத்தேள்

## Kural 234-7

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்றாது புத்தேள் உல

## Kural 234-7

### நிலவரை நீள்புகழ் ஆற்றின் புலவரைப்
### போற்றாது புத்தேள் உலகு

# Kural 245

## Kural 245-1

### அல்

## Kural 245-1

### அல்லல்

## Kural 245-2

### அல்லல் அரு

## Kural 245-2

### அல்லல் அருளாள்

## Kural 245-2

### அல்லல் அருளாள்வார்க்

## Kural 245-3

### அல்லல் அருளாள்வார்க் கில்

## Kural 245-3

### அல்லல் அருளாள்வார்க் கில்லை

## Kural 245-4

### அல்லல் அருளாள்வார்க் கில்லை வளி

## Kural 245-4

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்

## Kural 245-4

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்

## Kural 245-5

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்
### மல்

## Kural 245-5

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்
### மல்லன்

## Kural 245-5

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்
### மல்லன்மா

## Kural 245-6

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்
### மல்லன்மா ஞா

## Kural 245-6

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்
### மல்லன்மா ஞாலங்

## Kural 245-7

### அல்லல் அருளாள்வார்க் கில்லை வளிவழங்கும்
### மல்லன்மா ஞாலங் கரி
