---
title: "Batch 1 - Age 5 to 7 years"
format: html
---

# To join the Whatsapp group

Please use this [Whatsapp Invitation Link](https://chat.whatsapp.com/DhWghouzZoz68wjbQRsukg) to join the Whatsapp group where updates and discussions about the class sessions for the batch 1 - Age 5 to 7 years can be discussed.

# Inauguration day on 01/10/2023

# Term 1  

## Kurals on 15/10/2023

- **குணம்**நாடிக் **குற்ற**மு**ம்** நாடி அவற்றுள்  
மிகைநாடி **மிக்க** கொளல். 504  
- **தீ**யினாற் சுட்ட **புண்** உள்ளாறும் ஆறாதே  
**நா**வினாற் சுட்ட **வடு**. 128  

[Homework](homework-batch1.qmd##class1)

## Kurals on 29/10/2023

- **முக**நக நட்பது நட்பன்று நெஞ்சத்து  
**அக**நக நட்பது **நட்பு**. 786  
- யாகவராயினும் **நாகாக்க** காவாக்கால்  
சோகப்பர் சொல்லிழுக்குப் பட்டு. 127  

[Homework](homework-batch1.qmd##class2)

## Kurals on 12/11/2023

Cancelled due to Deepavali

## Kurals on 26/11/2023

- பிறர்க்கின்னா முற்பகல் செய்யின் தமக்கின்னா  
பிற்பகல் தாமே வரும். 319  
- மகன்தந்தைக்கு ஆற்றும் உதவி இவன்தந்தை  
என்நோற்றான் கொல்எனும் சொல். 70  
- இனிய உளவாக இன்னாத கூறல்  
கனிஇருப்பக் காய்கவர்ந் தற்று. 100  

## Kurals on 07/01/2024

- மனத்துக்கண் மாசிலன் ஆதல் அனைத்தறன்  
ஆகுல நீர பிற. 34  

- அழுக்காறு அவாவெகுளி இன்னாச்சொல் நான்கும்  
இழுக்கா இயன்றது அறம். 35  

## Kurals on 21/01/2024

- வையத்துள் வாழ்வாங்கு வாழ்பவன் வான்உறையும்  
தெய்வத்துள் வைக்கப் படும். 50  

- அல்லவை தேய அறம்பெருகும் நல்லவை  
நாடி இனிய சொலின். 96  

## Kurals on 04/02/2024

- அரம்போலும் கூர்மைய ரேனும் மரம்போல்வர்  
மக்கட்பண்பு இல்லா தவர். 997  

- உடையார்முன் இல்லார்போல் ஏக்கற்றுங் கற்றார்  
கடையரே கல்லா தவர்.  395  

 - அன்பிலார் எல்லாந் தமக்குரியர் அன்புடையார்  
என்பும் உரியர் பிறர்க்கு. 72  

- தினைத்துணை நன்றி செயினும் பனைத்துணையாக்  
கொள்வர் பயன்தெரி வார். 104  

- பிறர்க்குஇன்னா முற்பகல் செய்யின் தமக்குஇன்னா  
பிற்பகல் தாமே வரும். 319  

- மருந்தென வேண்டாவாம் யாக்கைக்கு அருந்தியது  
அற்றது போற்றி உணின். 942  


