---
title: "Summer 2024"
format: html
---

# Complete Study Guide

[Thirukkural Study Guide](thirukkural_study_guide.qmd) html page contains the summary of all slides used during the summer 2024 class with referrences to individual word meanings and usage examples of each words from other kurals with their links to support explorative, interactive curiosity lead learning.  

# Summer Class Syllabus

Kural Numbers - 1,12,23,34,45,56,67,78,89,100,101,112,123,134,145,156,167,178,189,200,201,212,223,234,245

[Class 1 - Kurals 1, 12, 23, 34, 45](thirukkural_kurals_1_to_5.qmd)  
[Class 2 - Kurals 56, 67, 78, 89, 100](thirukkural_kurals_6_to_10.qmd)  
[Class 3 - Kurals 101, 112, 123, 134, 145](thirukkural_kurals_11_to_15.qmd)  
[Class 4 - Kurals 156, 167, 178, 189, 200](thirukkural_kurals_16_to_20.qmd)  
[Class 5 - Kurals 201, 212, 223, 234, 245](thirukkural_kurals_21_to_25.qmd)  

```{mermaid}
graph LR
    A["Understand that"] --> B["Letters"]
    B --> |start|B1["Beginning"]
    A --> C["Curiosity"]
    C --> |act|C1["Reading Writing - Create"]
    A --> D["Humility"]
    D --> |stay|D1["Peaceful Heart, Silent Creation"]
    A --> E["Small"]
    E -->|distractions| E1["likes & Dislikes"]
    A --> F["Big"]
    F --> |difficulty|F1["Beyond Darkness"]
    F1 -->|focus|F2["Purpose"]
    A --> G["Important"]
    G --> |way|G1["Discipline"]
    G --> |rare|G2["Consistency"]
    A --> H["Knowing"]
    H --> |understand|H1["Virtues"]
    A --> I["Following"]
    I --> |define yourself with|I1["Values"]
    A --> J["Greatness"]
    J --> |needs|J1["Guidance"]
```

```{mermaid}
graph LR
A["Flow & Follow"] --> K["Rain"]
    A --> L["Great People"]
    A --> M["Virtue அறம்"]
    M --> M0["இல்லறம்"]
    M0["இல்லறம்"] --> M1["அம்மா-அப்பா-குழந்தைகள்"]
    M0 --> M2["மனம்"]
    M2 --> M3["அன்பு"]
    M0 --> M4["செயல்"]
    M4 --> M5["விருந்தோம்பல்"]
    M0 --> M6["சொல்"]
    M6 --> M7["இனிமை"]
    O --> N["Thankfulness"]
    O --> N1["Beyond Excuses"]
    M0 --> O["Great Character"]
    O --> O1["அடக்கம் - Discipline"]
    M0 --> O2["ஒழுக்கம் - Consistency"]
    O2 --> O1
    O1 --> P0["Anticipate and Prepare"]
    P0 --> P["Avoiding Easy Actions"]
    M22 --> Q["Patience"]
    %%A --> S["Goal"]
    O1 --> T["Leads to"]
    P0 --> M22["மனம்"]
    M22 --> U1["அழுக்காறாமை"]
    M22 --> U["வெஃகாமை"]
    P0 --> M66["சொல்"]
    M66 --> U3["புறங்கூறாமை"]
    M66 --> U2["பயனில சொல்லாமை"]
    P0 --> M44["செயல்"]
    M44 --> U4["தீவினையச்சம்"]
    A4 --> R["Good Actions"]
    R --> A1["ஒப்புரவறிதல்"]
    R --> A2["ஈகை"]
    A2 --> A3["புகழ்"]
    %%S --> A3
    T --> A4["அருளுடைமை"]
```

```{mermaid}
graph LR
    M0["இல்லறம்"] --> M1["அம்மா-அப்பா-குழந்தைகள்"]
    M0 --> M2["மனம்"]
    M2 --> M3["அன்பு"]
    M0 --> M4["செயல்"]
    M4 --> M5["விருந்தோம்பல்"]
    M0 --> M6["சொல்"]
    M6 --> M7["இனிமை"]
    O --> N["Thankfulness"]
    O --> N1["Beyond Excuses"]
    M0 --> O["Great Character"]
    O --> O1["அடக்கம் - Discipline"]
    M0 --> O2["ஒழுக்கம் - Consistency"]
    O2 --> O1
```

```{mermaid}
flowchart LR
    P0["Anticipate and Prepare"] --> P["Avoiding Easy Actions"]
    M22 --> Q["Patience"]
    P0 --> M22["மனம்"]
    M22 --> U1["அழுக்காறாமை"]
    M22 --> U["வெஃகாமை"]
    P0 --> M66["சொல்"]
    M66 --> U3["புறங்கூறாமை"]
    M66 --> U2["பயனில சொல்லாமை"]
    P0 --> M44["செயல்"]
    M44 --> U4["தீவினையச்சம்"]
```
# Words Reading with Asai

In Class 1, we will learn the syllables in all words in [Kural 1](kuralQuartoWordsAsaiContent1.qmd), [Kural 12](kuralQuartoWordsAsaiContent12.qmd), [Kural 23](kuralQuartoWordsAsaiContent23.qmd), [Kural 34](kuralQuartoWordsAsaiContent34.qmd), [Kural 45](kuralQuartoWordsAsaiContent45.qmd)  

In Class 2, we will learn the syllables in all words in [Kural 56](kuralQuartoWordsAsaiContent56.qmd), 
[Kural 67](kuralQuartoWordsAsaiContent67.qmd), [Kural 78](kuralQuartoWordsAsaiContent78.qmd), [Kural 89](kuralQuartoWordsAsaiContent89.qmd), [Kural 100](kuralQuartoWordsAsaiContent100.qmd)  

    - We covered also examples in duality.

In Class 3, we will learn syllables in all words in [Kural 101](kuralQuartoWordsAsaiContent101.qmd), [Kural 112](kuralQuartoWordsAsaiContent112.qmd), [Kural 123](kuralQuartoWordsAsaiContent123.qmd), [Kural 134](kuralQuartoWordsAsaiContent134.qmd), [Kural 145](kuralQuartoWordsAsaiContent145.qmd)    

In Class 4, we will learn syllables in all words in [Kural 156](kuralQuartoWordsAsaiContent156.qmd), 
[Kural 167](kuralQuartoWordsAsaiContent167.qmd), [Kural 178](kuralQuartoWordsAsaiContent178.qmd), [Kural 189](kuralQuartoWordsAsaiContent189.qmd), [Kural 200](kuralQuartoWordsAsaiContent200.qmd)  

In Class 5, we will learn syllables in all words in [Kural 201](kuralQuartoWordsAsaiContent201.qmd), [Kural 212](kuralQuartoWordsAsaiContent212.qmd), [Kural 223](kuralQuartoWordsAsaiContent223.qmd), [Kural 234](kuralQuartoWordsAsaiContent234.qmd) [and Kural 233](kuralQuartoWordsAsaiContent233.qmd)  , [Kural 245](kuralQuartoWordsAsaiContent245.qmd) [and Kural 242](kuralQuartoWordsAsaiContent242.qmd)  

# Learning words based on POS

[Nouns](thirukkural_noun_words.qmd)  
[Verbs](thirukkural_verb_words.qmd)  
[Adjectives](thirukkural_adjective_words.qmd)  
[Adverbs](thirukkural_adverb_words.qmd)  
[Postposition](thirukkural_postposition_words.qmd)  
[Pronoun](thirukkural_pronoun_words.qmd)  

# Homeworks

1. [What are the examples for Duality](duality.qmd)  
2. Meanings of all words in Kurals covered in class 1 and 2

# Claude Lessons

[Simple words](simple-words.qmd)  
[Lesson 1](lesson1.qmd)  
[Lesson 2](lesson2.qmd)  
[Lesson 3](lesson3.qmd)  
[Lesson 4](lesson4.qmd)  
[Lesson 5](lesson5.qmd)  
[Lesson 6](lesson6.qmd)  
[Lesson 7](lesson7.qmd)  
[Lesson 8](lesson8.qmd)  
[Lesson 9](lesson9.qmd)  
[Lesson 10](lesson10.qmd)  
[Lesson 1-1](lesson1-1.qmd)  
[Lesson 1-2](lesson1-2.qmd)  
[Lesson 1-3](lesson1-3.qmd)  
[Lesson 1-4](lesson1-4.qmd)  
[Lesson 1-5](lesson1-5.qmd)  
[Lesson 1-6](lesson1-6.qmd)  
[Lesson 1-7](lesson1-7.qmd)  
[Lesson 1-8](lesson1-8.qmd)  
[Lesson 1-9](lesson1-9.qmd)  
[Lesson 1-10](lesson1-10.qmd)  

## History

1. Navigation Added 
2. Asai wise presentation added
3. Add mindmap
4. Add Complete Study Guide
5. Fix missing links to reference kurals